language: ruby

rvm:
  - 2.0.0

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  - sudo apt-get update
  - sudo apt-get install dnsutils
  - rvm @global do gem uninstall bundler -x && gem install bundler -v '~> 1.5.2'  # For Vagrant 1.5
